### ISSUE TITLE
Erro ortográfico no gráfico de Análise Temática por Gênero

### ISSUE THREAD

**Issue by EduardoMoreira** [MES-1-2016/radar#12]
Na área de explicação do gráfico de Análise Temática por Gênero o texto é:
- "Trata-se de uma visualização de dados nuvem de palavras em que são apresentadas as palavras **150** temáticas mais frequentes ..."

Contudo, o texto deve ser:
- "Trata-se de uma visualização de dados nuvem de palavras em que são apresentadas as **150** palavras temáticas mais frequentes"

Trocando a palavra **150** de lugar no texto.

**Comment by luishng** [comment]
Pull request foi realizado para master do radar e pode ser acompanhado no link a seguir: https://github.com/radar-parlamentar/radar/pull/347
