### ISSUE TITLE
"Análise avançada"

### ISSUE THREAD

**Issue by EduardoMoreira** [MES-1-2016/radar#4]
Issue original: https://github.com/radar-parlamentar/radar/issues/329

Hoje temos duas opções de análises avançadas: definir periodicidade e filtro por palavras-chaves.

Essas duas opções hoje são difíceis de serem usadas em conjunto (ex: mostrar análise anual dos resultados relativos a "saúde").

Considerando que novas opções de análises avançadas podem surgir (#330), seria melhor que:

1) Houvesse um botão de submissão do formulário de análise avançada, em vez de a alteração do combobox da periodicidade já disparar uma requisição.

2) Todas as opções de análise avançada deveriam a princípio estar escondidas, e só aparecem na tela após o usuário clicar no texto "análise avançada".

**Comment by JonathanRufino** [comment]
Pull request foi realizado para master do radar e pode ser acompanhado no link a seguir: https://github.com/radar-parlamentar/radar/pull/343

**Comment by EduardoMoreira** [comment]
Como proposto pela equipe do Radar, serão implementadas melhorias nesta issue: https://github.com/radar-parlamentar/radar/issues/329

> Sobre #343, uma sugestão se quiserem dar uma melhorada: logo depois que a pessoa usou a busca avançada e tá vendo o resultado da busca avançada, seria legal q o formulário da busca avançada estivesse visível com as opções que a pessoa utilizou, em vez de ficar escondido, pois ficando escondido dá uma impressão estranha de "será que funcionou?".

**Comment by EduardoMoreira** [comment]
Pull request foi realizado para o repositório do Radar Parlamentar e pode ser acompanhado no link a seguir: https://github.com/radar-parlamentar/radar/pull/346
