### ISSUE TITLE
Mostrar chefe do executivo

### ISSUE THREAD

**Issue by EduardoMoreira** [MES-1-2016/radar#5]
Issue original: https://github.com/radar-parlamentar/radar/issues/328

Mostrar uma texto indicando quais os "prefeitos" ou "presidentes" que exerceram a chefia do executivo durante o período exibido.

Acho que isso ajuda bastante o usuário a se situar na análise.

No caso, acho que o "cadastro" dos chefes de executivo pode ficar fixo no código, já que é uma coisa que só muda de dois em dois anos.

**Comment by EduardoMoreira** [comment]
Merge request realizado https://github.com/radar-parlamentar/radar/pull/351

**Comment by marcowilliam** [comment]
Melhorias para a issue sugeridas em https://github.com/radar-parlamentar/radar/issues/328

**Comment by edinhogomes** [comment]
Nova issue https://github.com/MES-1-2016/radar/issues/17 foi criada para tratar de melhoria
